### ISSUE TITLE
主题问题

### ISSUE THREAD

**Issue by 81519434** [94fzb/zrlog#1]
hexo-theme-next
这个主题似乎有点问题，进入文章内页变成了这个样子
![image](https://cloud.githubusercontent.com/assets/9690089/23843283/c0ef7350-07f5-11e7-8b23-d114506f00c9.png)

**Comment by 81519434** [comment]
可否将这个https://blog.zrlog.com/主题开源出来呢？
好喜欢你这个主题啊

**Comment by hibegin** [comment]
@81519434 hexo-next好像是有这个问题，由于评论这里一直使用的是多说，没有注意到没有使用多说的情况。应该是div的问题（在不该结束的地方结束了）， https://blog.zrlog.com 的底部的文字还是写死的， 所以没有公开的提供，这几天把她做成配置后就传到主题中心。

**Comment by 94fzb** [comment]
@81519434 hexo-next好像是有这个问题，由于评论这里一直使用的是多说，没有注意到没有使用多说的情况。应该是div的问题（在不该结束的地方结束了）， https://blog.zrlog.com 的底部的文字还是写死的， 所以没有公开的提供，这几天把她做成配置后就传到主题中心。

**Comment by 94fzb** [comment]
@81519434 现在  https://blog.zrlog.com 的主题已经了提供了，可以通过管理中心进行下载了。关于源码直接下载对应zip就是对应的源码了。
