### ISSUE TITLE
图片无法保存

### ISSUE THREAD

**Issue by Inon-zhang** [94fzb/zrlog#16]
用markdown图片无法保存,一直自动保存中.而且图片上传体验太差

**Comment by 94fzb** [comment]
是指的编辑状态下老是弹出自动保存成功，感觉碍眼，还是无法保存保存成功，上传失败是有安装七牛插件，还是直接使用服务器无法保存

@Inon-zhang

**Comment by 94fzb** [comment]
如何还存在，重新打开
