### ISSUE TITLE
摘要的自动截取太长 导致手机端样式问题

### ISSUE THREAD

**Issue by e-lionel** [94fzb/zrlog#17]
摘要有时候截取的很长  有时候忘记手动改摘要   今天发现微信点地址连接进入blog   过长的摘要会横向占据很长  导致出现横向的滚动条
估计手动输入一个长的摘要也会出现这个问题

**Comment by 94fzb** [comment]
是网址这类英文吗？这样还是比较容易的

**Comment by 94fzb** [comment]
https://github.com/94fzb/zrlog/commit/9a7309d676934dab61c820b19ff001d25972053e 默认主题在这次提交修复了， 这类问题处理方式基本都是 style 里面 word-wrap: break-word; 就可以了
