### ISSUE TITLE
怎么进入不了管理后台？

### ISSUE THREAD

**Issue by liuzhiwang** [94fzb/zrlog#2]

**Comment by 94fzb** [comment]
这样还真不知道咋个判断，1.6使用IE10好像会出现登陆成功后跳转地址不对的情况。可以尝试升级/下载最新的看看，或则是换个浏览器看看

如果还有问题，需要提供下你的tomcat控制台，程序的版本号（最好附带下对应的buildId），还有就是看看浏览器的控制是否错误信息

**Comment by liuzhiwang** [comment]
http://localhost:8080/admin/login?redirectFrom=http://localhost:8080/admin/index
浏览器就跳转到了这个链接。

**Comment by 94fzb** [comment]
@liuzhiwang 
是 ie 吗？ ie 下面为了安全不可以设置 cookie 的 domain为 localhost 可能会导致无法登陆，开发的话使用  git 的代码。 git 的代码默认是开发环境，在开发环境添加 domain 这个字段的。

可以换个浏览器试下。或者直接使用源代码启动。

**Comment by liuzhiwang** [comment]
我是git上直接拉的带呀，是mac，用safari和chrome都不行呀

**Comment by 94fzb** [comment]
@liuzhiwang 

看来你可能是使用的默认的数据密码吧，这个无法登陆多半是其他人改了后台管理用户名和密码了。 
通常这个仅是用来展示的，你需要的将WEB-INF/install.lock文件删除掉，然后重启tomcat,访问http://localhost:8080/ 完成安装向导吧。 

看来这个尽快的加到 README.md 里面了。

**Comment by 94fzb** [comment]
@liuzhiwang tomcat8.5 对 cookie 的 value 字段有要求，不能包含特殊字符 , 具体看 https://github.com/94fzb/zrlog/commit/e3105994b926045d4e3716f0e1f72f505a67241d
