### ISSUE TITLE
获取传输协议为什么要从X-Forwarded-Protocol取？

### ISSUE THREAD

**Issue by DarknessChaser** [94fzb/zrlog#20]
网络上用X-Forwarded-Proto的似乎更多一些。

**Comment by 94fzb** [comment]
的确改用 X-Forwarded-Proto (强迫症), 这个会在新的代码里面优先 使用 X-Forwarded-Proto, 作为一个改进吧

**Comment by DarknessChaser** [comment]
系统设计的时候考虑了https了嘛？部署https后甚至不能初始化

**Comment by 94fzb** [comment]
可能是你没有配置 

### nginx代理后静态文件找不到的问题

需要额外修改将代理前的Host给Tomcat容器（默认会被转化为127.0.0.1:8080这类地址）
Nginx 添加 proxy_set_header Host $host 到对应server配置项，或则是在http模块里面。

@DarknessChaser

**Comment by DarknessChaser** [comment]
我现在已经加了X-Forwarded-Protocol关键字了，还是不行我跑跑看看是什么问题。

**Comment by 94fzb** [comment]
测试过的, 你看程序的主页都是支持的

**Comment by 94fzb** [comment]
测试过的, 你看程序的主页都是支持的 @DarknessChaser

**Comment by 94fzb** [comment]
@DarknessChaser https://github.com/94fzb/zrlog/commit/f43d1be218b6ffeaaee71ec76ddd81ab344775ab 这次提交，已经修改了这个逻辑了
