### ISSUE TITLE
我官网下载的版本这里这里没有评论功能要更新到哪个版本才有？或者说可以加个评论功能？

### ISSUE THREAD

**Issue by caizhenxi** [94fzb/zrlog#21]
我官网下载的版本这里这里没有评论功能要更新到哪个版本才有？或者说可以加个评论功能？

**Comment by 94fzb** [comment]
管理后台看看对应的文章是不是开启了评论功能了, 可能使用 hexo 这个主题的话, 可能会没有评论框 @caizhenxi

**Comment by 94fzb** [comment]
有疑问可以 reopen
