### ISSUE TITLE
进入登陆界面，js获取不到函数，css获取不到样式

### ISSUE THREAD

**Issue by Ssisyphus** [94fzb/zrlog#3]
如题，安装完成后，点击管理跳转到的登陆界面
所有样式都没有，点击登陆也没有反应，
查看源码，发现css和js为空，没有获取到

**Comment by hibegin** [comment]
@Ssisyphus 有可能是你安装包的问题？ 最好上个截图方便发现问题。（包含浏览器的控制台的）
如果排除安装包的问题的话，可以试下是不是浏览器不兼容的问题。（使用firefox/chrome看下）
对了这里可以下载到最新的 http://dl.zrlog.com/release/

**Comment by 94fzb** [comment]
@Ssisyphus 有可能是你安装包的问题？ 最好上个截图方便发现问题。（包含浏览器的控制台的）
如果排除安装包的问题的话，可以试下是不是浏览器不兼容的问题。（使用firefox/chrome看下）
对了这里可以下载到最新的 http://dl.zrlog.com/release/

**Comment by Ssisyphus** [comment]
下了最新的安装包，也用的chrome浏览器，问题依旧
![Uploading QQ截图20170419105953.png…]()

**Comment by 94fzb** [comment]
@Ssisyphus 图没有看到额，不应该呀。

**Comment by 94fzb** [comment]
@Ssisyphus 这边好像是有这个bug，不过很少用 window，刚用window才发现这个问题。可能  你用这个版本不会有这个问题. http://dl.zrlog.com/release/zrlog-1.6.3-2d57c0c-release.war

**Comment by 94fzb** [comment]
@Ssisyphus https://github.com/94fzb/zrlog/commit/58173bb69d48b8f1860cc090fefb55eb233f555c 已经修复了，原因 window 的文件系统的分隔符是 \  导致的。

**Comment by Ssisyphus** [comment]
用你刚才发的版本解决了，但是却出现了issues2的问题

**Comment by Ssisyphus** [comment]
hhh，可以了，非常感谢
