### ISSUE TITLE
总结问题

### ISSUE THREAD

**Issue by hanchun995** [94fzb/zrlog#31]

**Comment by hanchun995** [comment]
1.发布文章，如果不含头图片，在首页无法显示文章。
2.无新增标签按钮
3.无新增分类按钮

**Comment by 94fzb** [comment]
@hanchun995 谢谢反馈
1. 不一定要头图片吧，如果是在草稿状态是不会显示的
2. 标签是系统自己维护，要加在文章撰写页面填就可以了
3. 新建分类按钮被二级菜单遮住了，要新建，收起二级菜单就看到了

**Comment by hanchun995** [comment]
了解了，谢谢回复

**Comment by 94fzb** [comment]
那我关闭了，有新的问题再新建 issues
