### ISSUE TITLE
写文章图片功能

### ISSUE THREAD

**Issue by hanchun995** [94fzb/zrlog#32]
本地复制文档内容，在后台编辑框粘贴，无法显示图片，这个需要上传我能理解。
但是我复制网络上比如csdn的文档，在后台编辑中粘贴，能否根据这个url下载后嵌入在编辑框中，因为一个一个上传真的很麻烦，是否可以批量上传后，在根据上传的图片管理进行插入？

**Comment by 94fzb** [comment]
是指的非本站的图片链接本地化（保存到自己的服务器）吗？ @hanchun995

**Comment by hanchun995** [comment]
@94fzb  是的，如果是网络图片链接的话，自动下载保存在自己服务器，并且替换网络图片链接，不知道这个能否实现。如果是本地的文档复制直接粘贴的话，其中的图片还有没有更好的方法。

**Comment by 94fzb** [comment]
图片本地化倒是比较容易实现，仅需要在保存的时候服务端检查html是否包含了外站的图片，用户 httputil 把图片拉下来，同时调用 uploadService 的 getCloudUrl 就可以了，同时返回替换 markdown 文本和 content 文本，页面覆盖 markdown 就可以了，富文本编辑用新的 content 进行覆盖，但是会出现无法获取的情况（网站防止盗链），还有自己承担图片保存和带宽呢，如果自己没有图床（云存储）的话，还是用第三方提供的地址吧
