### ISSUE TITLE
老哥,问一下控制层是这么注册的

### ISSUE THREAD

**Issue by hanchun995** [94fzb/zrlog#33]
为什么只要写个方法，就可直接访问了，在哪里注册的。这个是什么技术，可以告知一下，我可以查看一下相应的技术

**Comment by 94fzb** [comment]
这个技术是 JFinal 提供的，对应的代码应该看 JFinal 的 RouterMapper，用到的地方应该再 ZrLogConfig 这个类里面 @hanchun995

**Comment by 94fzb** [comment]
技术问题，非bug，或者新功能，直接QQ群里面问题就可以了
