### ISSUE TITLE
后台分类无法删除?

### ISSUE THREAD

**Issue by xugaoxiang** [94fzb/zrlog#35]
最新版本, 后台分类无法删除?

**Comment by 94fzb** [comment]
@xugaoxiang 如果这个分类下面还有文章的情况是无法删除，数据库使用了外键导致的。

**Comment by xugaoxiang** [comment]
@94fzb ,  
![image](https://user-images.githubusercontent.com/20057478/43178027-e87d1db4-8ffd-11e8-9379-48a69d59bc31.png),  管理后台去删除, 不起作用.

**Comment by xugaoxiang** [comment]
@94fzb , 很奇怪, 其他的都可以删, 就这篇死活删不了, 
![image](https://user-images.githubusercontent.com/20057478/43178102-40a962c2-8ffe-11e8-92ff-eaa6e9a924a9.png)

**Comment by 94fzb** [comment]
@xugaoxiang 有可能文章下面有评论的原因
