### ISSUE TITLE
安装玩letsencrypt后，评论报500错误？

### ISSUE THREAD

**Issue by xugaoxiang** [94fzb/zrlog#36]
最新版本，搭建好https后（letsencrypt+nginx+tomcat），评论回复就报500错误。

![image](https://user-images.githubusercontent.com/20057478/43558967-7887de80-963e-11e8-9516-31dae7211694.png)

**Comment by 94fzb** [comment]
@xugaoxiang 应该和 https 没有关系吧，这种 500 控制应该有错的，可能是版本问题，或者是数据库的问题，我用最新的 2.0.4 测试并没有错误

**Comment by xugaoxiang** [comment]
突然又可以用了, @94fzb 。
