### ISSUE TITLE
发布的文章左上角图标显示不出？

### ISSUE THREAD

**Issue by xugaoxiang** [94fzb/zrlog#4]
zrlog版本： 1.8.0 - d1f36bc (2017-12-12)
java版本： OpenJDK Server VM (1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
Apache Tomcat/8.5.23
Chrome版本： 63.0.3239.132（正式版本） （64 位）

文章内的图片显示正常，图片是存放在github上的，图标的地址拼接不对。

**Comment by 94fzb** [comment]
额，刚看了下，以确定是bug。 应该去抓github的图片的问题，多半是保存文件的问题 https://github.com/94fzb/zrlog/blob/master/src/main/java/com/zrlog/service/ArticleService.java 
String getFirstImgUrl() 这个里面没有把图片保存成功
