### ISSUE TITLE
标题怎么改呀

### ISSUE THREAD

**Issue by 1542254356** [94fzb/zrlog#40]
![default](https://user-images.githubusercontent.com/25589700/47611092-8d947100-da98-11e8-8844-e2222a57c74e.png)
这里的ip怎么修改为名字呀，设置里面改了标题副标题没用呀。

**Comment by 94fzb** [comment]
路径有点深 管理后台 -> 设置 -> 主题 -> 选择对应的主题，点击默认主题的那个 设置图标就能看到这个页面了
![image](https://user-images.githubusercontent.com/12691281/47617307-bb150500-db00-11e8-9268-8caea25756f0.png)

改成自己想要的，保存就可以了

**Comment by 1542254356** [comment]
哦哦，我下的是2.0.1，没有主题设置，我就说怎么找不到。

**Comment by 94fzb** [comment]
@1542254356 嗯，群里一直有人说找到添加分类的图标于是就把主题重更多里面移动到设置里面了（发现移动到设置里面更加合理一点）

**Comment by 94fzb** [comment]
@1542254356 先关闭了，有问题开的 issues
