### ISSUE TITLE
安装向导-一致失败

### ISSUE THREAD

**Issue by popsc30** [94fzb/zrlog#41]
首页 install时 安装向导-一致失败.
要么是 用户密码不对(实际是对的), 要么是没有创建表权限(用的root 最高权限)
然后 download 了份源码(改了 db 和删了 lock文件), 发现问题在:
SQLNonTransientConnectionException: CLIENT_PLUGIN_AUTH is required
也就是在 jdbc getConnection 时问题

环境: macOS + mysql 5.1 + jdk-8
环境2: Debian + mysql 5.5 + openJdk8

**Comment by 94fzb** [comment]
还有这问题呢，你使用的是 tomcat 吗？如果使用的 tomcat 检查下你的 tomcat 的 lib 目录里面是不是还有一个 mysql 的驱动包，如果存在删除了，再试下 @popsc30

**Comment by 94fzb** [comment]
@popsc30 或者尝试升级下的 mysql 版本，看看还有没有这个问题

**Comment by 94fzb** [comment]
已确定，zrlog 需要 5.7 即以后版本了
