### ISSUE TITLE
[Error-6] - 未知错误请联系作者

### ISSUE THREAD

**Issue by cq-Gang-Yu** [94fzb/zrlog#44]
宝塔面板tomcat9安装未知错误

**Comment by 94fzb** [comment]
@cq-Gang-Yu 你可以看看控制台日志，因为这个错误是在预期外的，才需要联系作者，之前有网友也遇到过，他升级到 MySQL 5.6 以后的版本就能正常安装了，提示的错误是 CLIENT_PLUGIN_AUTH is required

![image](https://user-images.githubusercontent.com/12691281/55388777-733e5200-5566-11e9-8a34-2893f767f224.png)
