### ISSUE TITLE
There is a Arbitrary file reading in the backend

### ISSUE THREAD

**Issue by Like0x** [94fzb/zrlog#46]
The problem exists in the error page editor.

![image](https://user-images.githubusercontent.com/19629138/55493774-2644a380-566c-11e9-858a-b264604ea269.png)

When clicking on any page modification, the system will read the relevant file content.

![image](https://user-images.githubusercontent.com/19629138/55493987-86d3e080-566c-11e9-965e-b6c409002695.png)

Observe the path to find the class file corresponding to the route in the code
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/19629138/55494208-ea5e0e00-566c-11e9-8ab6-4bd58d13b19b.png">

You can see that there is no filtering in the code

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/19629138/55494306-11b4db00-566d-11e9-9567-1eb466a6d3f4.png">
The code use  FileInputStream to load the file directly.

![image](https://user-images.githubusercontent.com/19629138/55494506-7a03bc80-566d-11e9-9996-4124862ea089.png)
```bash
/../../../../../etc/passwd
```
**Successfully read the file and return /etc/passwd**

**Comment by 94fzb** [comment]
Thanks . This need admin login. Will fix in next version
