### ISSUE TITLE
ZrLog 2.1.0产品后台存在文件写入漏洞

### ISSUE THREAD

**Issue by chenergy1991** [94fzb/zrlog#49]
漏洞详情页：
https://chenergy1991.github.io/2019/04/24/ZrLog%E5%90%8E%E5%8F%B0%E6%96%87%E4%BB%B6%E5%86%99%E5%85%A5/

**Comment by 94fzb** [comment]
@chenergy1991 下一个版本修复（对涉及文件修改的接口加白名单的方式）
