### ISSUE TITLE
评论数字角标不消失？

### ISSUE THREAD

**Issue by xugaoxiang** [94fzb/zrlog#5]
zrlog版本： 1.8.0 - d1f36bc (2017-12-12)
java版本： OpenJDK Server VM (1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
Apache Tomcat/8.5.23
Chrome版本： 63.0.3239.132（正式版本） （64 位）

查看，编辑，都无法消失。

**Comment by 94fzb** [comment]
谢谢， 这个也是bug，一致没有修改
