### ISSUE TITLE
使用jenkins构建报错com.zrlog.util.ZrLogUtil getConnection - com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

### ISSUE THREAD

**Issue by hans998123** [94fzb/zrlog#51]
使用jenkins构建报错com.zrlog.util.ZrLogUtil getConnection - com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
请问这是什么原因造成的，是我环境中没安装mysql?

**Comment by 94fzb** [comment]
@hans998123 并不是的，是因为你没有跳过测试用例导致的，默认是开着测试用例的，后面的版本还是关闭了好，构建的时候使用 mvn  -Dmaven.test.skip=false package
