### ISSUE TITLE
jenkins构建项目不成功

### ISSUE THREAD

**Issue by jacklu0516** [94fzb/zrlog#52]
构建完成后打包成war包，部署到tomcat访问失败，起初一直以为是打包过程出了问题。后台开发同事通检查了问题原因，后台通过在jenkins打包前将web/src/main/webapp/WEB-INF/install.lock文件进行删除，然后进行maven打包，部署到tomcat访问成功。请问这个文件功能是什么？没有错误提醒，找起原因来确实很麻烦。

**Comment by 94fzb** [comment]
这个文件是用与判断是否配置了数据裤用的，如果自己搭建的，直接用 mvn clean install 的 war 发布就可以，前提是你开发的数据个正式环境的数据库是一致的，不一致的话，打包完成后用 zip 命令把线上环境的数据库配置文件添加到 war 里面就可以了， 也可以下打 jar @jacklu0516

**Comment by jacklu0516** [comment]
好的，谢谢您的回复！


 
---原始邮件---
发件人: "xiaochun"<notifications@github.com>
发送时间: 2019年6月20日(星期四) 晚上11:42
收件人: "94fzb/zrlog"<zrlog@noreply.github.com>;
抄送: "jacklu0516"<657338686@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [94fzb/zrlog] jenkins构建项目不成功 (#52)



这个文件是用与判断是否配置了数据裤用的，如果自己搭建的，直接用 mvn clean install 的 war 发布就可以，前提是你开发的数据个正式环境的数据库是一致的，不一致的话，打包完成后用 zip 命令把线上环境的数据库配置文件添加到 war 里面就可以了， 也可以下打 jar @jacklu0516

**Comment by GD2YG188** [comment]
war包解压后WEB-INF的install.lock文件和build中的maven打包的命令有关么？
