### ISSUE TITLE
拉取最新代码打包失败，访问显示404

### ISSUE THREAD

**Issue by herrywen-nanj** [94fzb/zrlog#53]
![image](https://user-images.githubusercontent.com/33476935/62076109-6b26c280-b279-11e9-8802-56cb2fc466ed.png)
mvn版本3.6.1，jdk版本1.8,克隆代码后，在项目主目录下执行"mvn clean install -Dmaven.test.skip=true"，在target中生成对应war包
![image](https://user-images.githubusercontent.com/33476935/62076220-b17c2180-b279-11e9-9d41-88cb71de1bc2.png)
放在tomcat的webapps下，访问无法跳出安装界面，这是mvn版本太新导致的么？
![image](https://user-images.githubusercontent.com/33476935/62076359-146db880-b27a-11e9-96f1-a52193864409.png)

**Comment by 94fzb** [comment]
你的tomcat是用的zip包，还是maven里面内嵌的？如果是 zip 包的话，应该把打包出来的 war 放到 webapps 目录里面，线上环境用 zip 包，开发的话用命令行或者 sh bin/tomcat-run.sh 或者直接找到 Application.java 直接 idea 右键启动就可以了 @herrywen-nanj

**Comment by chenyunwow** [comment]
我的和你一样 放到web app下面 也是不行

**Comment by chenyunwow** [comment]
HTTP Status 404 – Not Found
Type Status Report

Message /zrlog-2.1.3

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/8.5.34

**Comment by herrywen-nanj** [comment]
您好，我的tomcat是编译安装的，其他项目的war包都可以正常显示。就是克隆您的master分支下来，用命令打包成war就不可以显示，具体命令在上面。直接去你们官网下载unzip的包也是可以的

**Comment by herrywen-nanj** [comment]
@94fzb

**Comment by 94fzb** [comment]
![image](https://user-images.githubusercontent.com/12691281/63859232-8b14e780-c9d9-11e9-868c-1eac90733891.png)


@herrywen-nanj  @chenyunwow  应该是容器的 context 不一致导致的，如果要用 maven 启动的话，建议直接使用项目里面的 sh bin/tomcat-run.sh 启动就可以了，发布的话个人推荐还是手动发布 war 包，如果一定要用 maven 发布的话，应该是把 web/pom.xml 里面的contextPath 改为和 final-name 一致就可以了。
