### ISSUE TITLE
There is a stored XSS in the article_edit area

### ISSUE THREAD

**Issue by xiaoxierhea** [94fzb/zrlog#54]

**Comment by xiaoxierhea** [comment]
![image](https://user-images.githubusercontent.com/35941559/65291715-2c313100-db87-11e9-96bf-d34bcde76443.png)

![image](https://user-images.githubusercontent.com/35941559/65291693-1459ad00-db87-11e9-9ad8-c5ca54405e94.png)

**Comment by 94fzb** [comment]
@xiaoxierhea 算 bug，不过怎么大家都喜欢在后台页面自己搞自己，不理解
