### ISSUE TITLE
前台文章评论处存储型XSS

### ISSUE THREAD

**Issue by T-pod** [94fzb/zrlog#56]
在2.1.3版本中，前台对文章评论处，可以插入获取管理员cookie的XSS语句，管理员访问登录后台即可触发XSS。
![image](https://user-images.githubusercontent.com/42511919/67159413-e2e72380-f376-11e9-89c7-6ef0dade1936.png)

![image](https://user-images.githubusercontent.com/42511919/67159399-b7643900-f376-11e9-9d58-eb1ff07386b4.png)

**Comment by 94fzb** [comment]
收到
