### ISSUE TITLE
发布新文章，页面右下角的归档没有更新

### ISSUE THREAD

**Issue by xugaoxiang** [94fzb/zrlog#6]
zrlog版本： 1.8.0 - d1f36bc (2017-12-12)
java版本： OpenJDK Server VM (1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
Apache Tomcat/8.5.23
Chrome版本： 63.0.3239.132（正式版本） （64 位）

今天刚刚写了3月份的第一篇文章，发布成功后页面可见，但是右下角的归档里没有出现3月份的。

**Comment by 94fzb** [comment]
这个有一个缓存在哪里，一般没有请求后一分钟缓存会失效的，最近在1.9.1上面再构建一个版本修复文章不更新缓存的问题，可以自己的，参考@RefreshCache这个注解

**Comment by xugaoxiang** [comment]
@94fzb , 还有一个类似的，就是管理里边的评论数角标，目前的意思是总评论数。一般的理解未读的数目。

**Comment by 94fzb** [comment]
@xugaoxiang https://gitee.com/94fzb/zrlog/commit/253851301d2c285b156c090244ced5d4bc880494 看这次提交
