### ISSUE TITLE
Arbitrary File Deletion Vulnerability in com.zrlog.web.controller.admin.api.TemplateController#delete

### ISSUE THREAD

**Issue by j1nse** [94fzb/zrlog#66]
There is a Arbitrary file deletion vulnerability in `com.zrlog.web.controller.admin.api.TemplateController#delete()` .
![image](https://user-images.githubusercontent.com/22301107/95892362-017cd080-0db9-11eb-93df-daeece0642f2.png)
The template can be any files include  folder. It is dangerous ,and hacker can delete the website and data.
1. upload a zip file in theme setting page:
2. delete it, and get the Post.
![image](https://user-images.githubusercontent.com/22301107/95893250-48b79100-0dba-11eb-89c1-0691e8a48d5e.png)
3. change the template variable and post.
![image](https://user-images.githubusercontent.com/22301107/95893877-e14e1100-0dba-11eb-8b52-0d96825fffdd.png)

![image](https://user-images.githubusercontent.com/22301107/95893757-af3caf00-0dba-11eb-87d6-b2ab56c42786.png)
![image](https://user-images.githubusercontent.com/22301107/95893774-b6fc5380-0dba-11eb-82a0-cba8dd6ba294.png)
4. the website is down
![image](https://user-images.githubusercontent.com/22301107/95893932-f7f46800-0dba-11eb-99cc-6094e25fbdaa.png)

**Comment by 94fzb** [comment]
已对输入参数进行检查
