### ISSUE TITLE
畅言插件无法停用

### ISSUE THREAD

**Issue by rongworld** [94fzb/zrlog#7]
畅言插件安装后停用删除，但是页面仍然提示“畅言代码无效，请检查文章链接所在域名是否填入畅言后台-系统设置-通用设置-域名白名单中。如非您的代码，请重新注册。”
重启无效

**Comment by 94fzb** [comment]
需要用手动停用下，卸载时并并没有还原状态

**Comment by 94fzb** [comment]
@rongworld 插件机制时这样的，如果有疑问 reopen
